"""add variant_question, practice_session_question, extend practice_session and student, review_task level to 0

Revision ID: 48462f130944
Revises: af2fbfbc1f0d
Create Date: 2026-08-07 12:07:52.422804
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48462f130944'
down_revision: Union[str, None] = 'af2fbfbc1f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_question_id', sa.Integer(), nullable=False, comment='原题 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目正文'),
    sa.Column('question_type', sa.String(length=30), server_default='choice', nullable=False, comment='题型'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表 JSON，非选择题为 null'),
    sa.Column('answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='题目解析'),
    sa.Column('knowledge_point_tags', sa.JSON(), nullable=True, comment='知识点标签数组'),
    sa.Column('difficulty', sa.String(length=20), server_default='medium', nullable=False, comment='难度等级'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='生成时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间（默认 90 天后）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['original_question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_session_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False, comment='练习会话'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_session_id', 'question_id', name='uq_psq_session_question')
    )
    with op.batch_alter_table('practice_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_id', sa.String(length=100), nullable=False, comment='业务标识符'))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False, comment='练习标题'))
        batch_op.add_column(sa.Column('question_count', sa.Integer(), server_default='0', nullable=False, comment='题目总数'))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='截止日期'))
        batch_op.create_unique_constraint('uq_practice_session_practice_id', ['practice_id'])

    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_correct', sa.Integer(), server_default='0', nullable=False, comment='连续答对次数'))
        batch_op.add_column(sa.Column('consecutive_wrong', sa.Integer(), server_default='0', nullable=False, comment='连续答错次数'))
        batch_op.alter_column('level', server_default='0')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weak_knowledge_points', sa.JSON(), nullable=True, comment="薄弱知识点列表，如 ['氧化还原反应', '离子反应']"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('weak_knowledge_points')

    with op.batch_alter_table('review_task', schema=None) as batch_op:
        batch_op.drop_column('consecutive_wrong')
        batch_op.drop_column('consecutive_correct')

    with op.batch_alter_table('practice_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('deadline')
        batch_op.drop_column('question_count')
        batch_op.drop_column('title')
        batch_op.drop_column('practice_id')

    op.drop_table('practice_session_question')
    op.drop_table('variant_question')
    # ### end Alembic commands ###
