"""phase2_data_model_and_auth

Revision ID: af2fbfbc1f0d
Revises: d724bd644b84
Create Date: 2026-08-03 14:12:44.109889
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2fbfbc1f0d'
down_revision: Union[str, None] = 'd724bd644b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ── Data migrations (before structural changes) ──

    # Map legacy question_type strings to new enum values
    op.execute("UPDATE question SET question_type = 'choice' WHERE question_type IN ('choice', 'single_choice', 'multi_choice')")
    op.execute("UPDATE question SET question_type = 'fill_blank' WHERE question_type IN ('fill', 'fill_blank', 'true_false')")
    op.execute("UPDATE question SET question_type = 'calculation' WHERE question_type IN ('calc', 'calculation', 'short_answer', 'essay')")
    op.execute("UPDATE question SET question_type = 'experiment_inquiry' WHERE question_type IN ('experiment', 'inference', 'experiment_inquiry')")

    # Map legacy difficulty strings to new 3-tier enum
    op.execute("UPDATE question SET difficulty = 'easy' WHERE difficulty IN ('easy', 'easy-medium')")
    op.execute("UPDATE question SET difficulty = 'medium' WHERE difficulty IN ('medium', 'medium-hard')")
    op.execute("UPDATE question SET difficulty = 'hard' WHERE difficulty = 'hard'")
    op.execute("UPDATE historical_exam SET difficulty = 'easy' WHERE difficulty IN ('easy', 'easy-medium')")
    op.execute("UPDATE historical_exam SET difficulty = 'medium' WHERE difficulty IN ('medium', 'medium-hard')")
    op.execute("UPDATE historical_exam SET difficulty = 'hard' WHERE difficulty = 'hard'")

    # ── Structural changes ──

    op.create_table('approval_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False, comment='对话线程 ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='触发审批的 tool 名称'),
    sa.Column('tool_params', sa.JSON(), nullable=False, comment='冻结时的参数快照'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='审批状态：pending / approved / rejected / expired'),
    sa.Column('requested_by', sa.Integer(), nullable=False, comment='Agent 代表的教师'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='审批教师'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='超时时间（超时后自动 expired）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['approved_by'], ['teacher.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_request_thread_id'), ['thread_id'], unique=False)

    op.create_table('exam_paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='试卷名称'),
    sa.Column('total_score', sa.Integer(), server_default='100', nullable=False, comment='试卷总分'),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False, comment='考试时限（分钟）'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='状态：draft / published / archived'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='创建教师'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_paper_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_paper_id', sa.Integer(), nullable=False, comment='试卷'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序序号'),
    sa.Column('score', sa.Float(), server_default='0.0', nullable=False, comment='该题在此试卷中的分值'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['exam_paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_paper_id', 'question_id', name='uq_epq_paper_question')
    )
    op.create_table('practice_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生'),
    sa.Column('barrier_type', sa.String(length=20), nullable=False, comment='本次练习针对的障碍类型'),
    sa.Column('knowledge_point_tags', sa.JSON(), nullable=True, comment='覆盖的知识点标签数组'),
    sa.Column('questions_served', sa.Integer(), server_default='0', nullable=False, comment='推送题目数'),
    sa.Column('questions_correct', sa.Integer(), server_default='0', nullable=False, comment='答对题目数'),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False, comment='状态：in_progress / completed / abandoned'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Account: add phone column (SQLite native ADD COLUMN), then batch for index + drop
    op.execute("ALTER TABLE account ADD COLUMN phone VARCHAR(20)")
    op.execute("UPDATE account SET phone = username WHERE phone IS NULL")
    op.execute("UPDATE account SET phone = 'unknown_' || CAST(id AS TEXT) WHERE phone IS NULL")

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('phone', nullable=False, existing_type=sa.String(20))
        batch_op.drop_index(batch_op.f('ix_account_username'))
        batch_op.create_index(batch_op.f('ix_account_phone'), ['phone'], unique=True)
        batch_op.drop_column('username')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('head_teacher_id')

    with op.batch_alter_table('exam_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_paper_id', sa.Integer(), nullable=True, comment='关联试卷模板（可为空，手动组卷场景）'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='状态：pending / in_progress / grading / completed / archived / cancelled'))
        batch_op.create_foreign_key('fk_exam_record_paper', 'exam_paper', ['exam_paper_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('knowledge_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True, comment='父知识点 ID（自引用，构建层级树）'))
        batch_op.create_foreign_key('fk_kp_parent', 'knowledge_point', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_of_question_id', sa.Integer(), nullable=True, comment='变体蓝本题 ID（自引用）'))
        batch_op.add_column(sa.Column('variant_dimensions', sa.JSON(), nullable=True, comment='变体维度：{value, substance, stem, options, difficulty}'))
        batch_op.create_foreign_key('fk_question_variant', 'question', ['variant_of_question_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True, comment='所属学校（冗余，加速数据隔离查询）'))
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True, comment='学号，与 school_id 组合全局唯一'))
        batch_op.add_column(sa.Column('is_activated', sa.Boolean(), server_default='0', nullable=False, comment='是否已激活（首次登录后置 True）'))
        batch_op.drop_column('phone')

    # Populate existing rows with default values
    op.execute("UPDATE student SET school_id = 1, student_id = 'LEGACY_' || CAST(id AS TEXT) WHERE school_id IS NULL")

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('school_id', nullable=False)
        batch_op.alter_column('student_id', nullable=False)
        batch_op.create_unique_constraint('uq_student_school_student_id', ['school_id', 'student_id'])
        batch_op.create_foreign_key('fk_student_school', 'school', ['school_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('misconception_category', sa.String(length=30), nullable=True, comment='迷思概念类别（3×6 诊断矩阵第二维）'))
        batch_op.add_column(sa.Column('diagnosed_by', sa.String(length=20), nullable=True, comment='诊断来源：ai_rule / ai_llm / teacher'))
        batch_op.add_column(sa.Column('diagnosis_overridden_at', sa.DateTime(timezone=True), nullable=True, comment='教师覆盖诊断的时间'))
        batch_op.alter_column('exam_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='加密密码（审批通过后复制到 Account）'))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True, comment='申请学校'))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)

    # Populate existing rows
    op.execute("UPDATE teacher_application SET school_id = 1, password_hash = '' WHERE school_id IS NULL")

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.alter_column('password_hash', nullable=False)
        batch_op.alter_column('school_id', nullable=False)
        batch_op.create_foreign_key('fk_teacher_app_school', 'school', ['school_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ── Reverse structural changes ──
    # Order: reverse column changes on existing tables FIRST (removes FKs to new tables),
    # THEN drop new tables.

    # Reverse column changes on existing tables
    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.drop_column('school_id')
        batch_op.drop_column('password_hash')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), nullable=True))

    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.alter_column('exam_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('diagnosis_overridden_at')
        batch_op.drop_column('diagnosed_by')
        batch_op.drop_column('misconception_category')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('school_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('is_activated')
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('variant_dimensions')
        batch_op.drop_column('variant_of_question_id')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), nullable=True))

    with op.batch_alter_table('knowledge_point', schema=None) as batch_op:
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('exam_record', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('exam_paper_id')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_teacher_id', sa.INTEGER(), nullable=True))

    # Account: add back username, drop phone
    op.execute("ALTER TABLE account ADD COLUMN username VARCHAR(100)")
    op.execute("UPDATE account SET username = COALESCE(phone, 'user_' || CAST(id AS TEXT))")

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.drop_index(batch_op.f('ix_account_phone'))
        batch_op.create_index(batch_op.f('ix_account_username'), ['username'], unique=True)
        batch_op.drop_column('phone')

    # Drop new tables (after FK references are removed)
    op.drop_table('practice_session')
    op.drop_table('exam_paper_question')
    op.drop_table('exam_paper')
    with op.batch_alter_table('approval_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_request_thread_id'))
    op.drop_table('approval_request')
    # ### end Alembic commands ###
