"""initial: 27 tables

Revision ID: d724bd644b84
Revises: 
Create Date: 2026-08-01 12:56:33.133998
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd724bd644b84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='全局唯一用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='账户角色：teacher / student / parent'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_username'), ['username'], unique=True)

    op.create_table('historical_exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False, comment='试卷来源，如 全国卷/湖南卷'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('question_number', sa.String(length=20), nullable=True, comment='题号'),
    sa.Column('knowledge_point_tags', sa.JSON(), nullable=True, comment='知识点标签数组'),
    sa.Column('difficulty', sa.String(length=20), server_default='medium', nullable=False, comment='难度'),
    sa.Column('discrimination', sa.Float(), nullable=True, comment='区分度（统计指标）'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目正文'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='解析'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识点名称'),
    sa.Column('category', sa.String(length=200), nullable=True, comment='所属分类，如 电解质溶液'),
    sa.Column('pubchem_id', sa.String(length=50), nullable=True, comment='关联 PubChem 化合物编号'),
    sa.Column('question_count', sa.Integer(), server_default='0', nullable=False, comment='关联题目数'),
    sa.Column('dynamic_error_rate', sa.Float(), server_default='0.0', nullable=False, comment='动态错误率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='题目正文'),
    sa.Column('question_type', sa.String(length=30), server_default='choice', nullable=False, comment='题型：choice / fill / calc / experiment / inference'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项列表 JSON，非选择题为 null'),
    sa.Column('answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='题目解析'),
    sa.Column('knowledge_point_tags', sa.JSON(), nullable=True, comment='知识点标签数组'),
    sa.Column('difficulty', sa.String(length=20), server_default='medium', nullable=False, comment='难度：easy / medium / hard / competition'),
    sa.Column('source', sa.String(length=30), server_default='manual', nullable=False, comment='题目来源：ai_generated / manual / daily_practice / ocr_import'),
    sa.Column('audit_status', sa.String(length=20), server_default='passed', nullable=False, comment='审核状态：passed / warning / blocked'),
    sa.Column('audit_report', sa.JSON(), nullable=True, comment='审核报告 JSON：四维度 + 综合判定 + 审核耗时'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='学校全称'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='所在地区'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='详细地址'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='联系电话'),
    sa.Column('current_semester', sa.String(length=50), nullable=True, comment='当前学期，如 2026春'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False, comment='所属学校'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='年级名称，如 高一/高二/高三'),
    sa.Column('academic_year', sa.String(length=20), nullable=True, comment='学年，如 2025-2026'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_grade_school_name')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='关联账户'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='家长姓名'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='手机号码'),
    sa.Column('email', sa.String(length=200), nullable=True, comment='电子邮箱'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='关联账户'),
    sa.Column('school_id', sa.Integer(), nullable=False, comment='所属学校'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='教师姓名'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='手机号码'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='账号状态：pending / approved / rejected'),
    sa.Column('role', sa.String(length=30), server_default='teacher', nullable=False, comment='教师子角色：system_admin / academic_admin / subject_lead / teacher'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('barrier_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师（一对一）'),
    sa.Column('concept_threshold', sa.Integer(), server_default='3', nullable=False, comment='概念理解型障碍触发阈值：同一知识点连续答错 N 次'),
    sa.Column('reading_threshold', sa.Integer(), server_default='2', nullable=False, comment='审题障碍型触发阈值'),
    sa.Column('expression_threshold', sa.Integer(), server_default='3', nullable=False, comment='表述障碍型触发阈值'),
    sa.Column('mastery_threshold', sa.Integer(), server_default='3', nullable=False, comment='掌握标准：同一知识点连续答对 N 次'),
    sa.Column('auto_sync_enabled', sa.Boolean(), server_default='0', nullable=False, comment='诊断结论是否自动推送给学生端'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False, comment='所属年级'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='班级名称，如 高一(3)班'),
    sa.Column('head_teacher_id', sa.Integer(), nullable=True, comment='班主任'),
    sa.Column('student_count', sa.Integer(), server_default='0', nullable=False, comment='当前学生人数'),
    sa.Column('stage', sa.String(length=20), nullable=True, comment='学段：高中/初中'),
    sa.Column('subject', sa.String(length=50), server_default='化学', nullable=False, comment='学科（本平台聚焦化学）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['head_teacher_id'], ['teacher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id', 'name', name='uq_class_grade_name')
    )
    op.create_table('parent_notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='家长'),
    sa.Column('notification_type', sa.String(length=30), nullable=False, comment='通知类型'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('body', sa.Text(), nullable=False, comment='通知正文'),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False, comment='已读状态'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False, comment='发送时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='创建教师'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='文件夹名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='申请人姓名'),
    sa.Column('phone', sa.String(length=30), nullable=False, comment='手机号码'),
    sa.Column('school_name', sa.String(length=200), nullable=False, comment='学校名称'),
    sa.Column('subject', sa.String(length=50), server_default='化学', nullable=False, comment='教授学科'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='审批状态：pending / approved / rejected'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审批人（admin）'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='审批完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['teacher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='上传教师'),
    sa.Column('status', sa.String(length=20), server_default='uploaded', nullable=False, comment='会话状态'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='处理完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='所属班级'),
    sa.Column('exam_type', sa.String(length=20), nullable=False, comment='考试类型：monthly / practice / homework'),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False, comment='考试日期'),
    sa.Column('participant_count', sa.Integer(), server_default='0', nullable=False, comment='参考人数'),
    sa.Column('avg_score', sa.Float(), nullable=True, comment='平均分'),
    sa.Column('error_stats', sa.JSON(), nullable=True, comment='错题统计 JSON：逐题错误率 + 知识点排行 + 班级平均分'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='考试名称，如 高一期末模拟考'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_session_id', sa.Integer(), nullable=False, comment='所属上传会话'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='任务状态：pending / processing / done / failed'),
    sa.Column('ocr_raw_result', sa.JSON(), nullable=True, comment='OCR 原始识别结果'),
    sa.Column('grading_result', sa.JSON(), nullable=True, comment='批改结果：逐题判定 + 汇总统计'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_set_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_set_id', sa.Integer(), nullable=False, comment='题库文件夹'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_set_id', 'question_id', name='uq_qsi_set_question')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='关联账户'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='所属班级'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='学生姓名'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='手机号码'),
    sa.Column('status', sa.String(length=20), server_default='approved', nullable=False, comment='账号状态：pending / approved / rejected'),
    sa.Column('barrier_profile', sa.JSON(), nullable=True, comment='障碍画像 JSON：{concept, reading, expression} 占比和=1'),
    sa.Column('barrier_profile_updated_at', sa.DateTime(timezone=True), nullable=True, comment='障碍画像最后更新时间'),
    sa.Column('practice_count', sa.Integer(), server_default='0', nullable=False, comment='累计完成练习数'),
    sa.Column('last_practice_time', sa.DateTime(timezone=True), nullable=True, comment='最近练习时间'),
    sa.Column('bind_code', sa.String(length=6), nullable=True, comment='6 位家长绑定码'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('bind_code')
    )
    op.create_table('teacher_class_subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='班级'),
    sa.Column('subject', sa.String(length=50), server_default='化学', nullable=False, comment='教授学科'),
    sa.Column('is_head_teacher', sa.Boolean(), server_default='0', nullable=False, comment='是否班主任'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', name='uq_tcs_teacher_class')
    )
    op.create_table('conversation_checkpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False, comment='对话线程 ID，如 conv_abc123'),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='关联学生（如有）'),
    sa.Column('checkpoint_data', sa.JSON(), nullable=False, comment='检查点数据：消息历史 + Agent 状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_checkpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_checkpoint_thread_id'), ['thread_id'], unique=False)

    op.create_table('long_term_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='关联学生'),
    sa.Column('teacher_id', sa.Integer(), nullable=True, comment='关联教师'),
    sa.Column('memory_type', sa.String(length=50), nullable=False, comment='记忆类型'),
    sa.Column('content', sa.JSON(), nullable=False, comment='记忆内容 JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='错题'),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False, comment='当前复习级别：1~5 递进，6=已掌握'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='状态：pending / overdue / completed'),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True, comment='下次复习日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目'),
    sa.Column('exam_record_id', sa.Integer(), nullable=False, comment='所属考试'),
    sa.Column('answer_content', sa.Text(), nullable=False, comment='学生作答内容'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否正确'),
    sa.Column('barrier_type', sa.String(length=20), nullable=True, comment='诊断引擎判定的障碍类型'),
    sa.Column('consecutive_wrong_count', sa.Integer(), server_default='0', nullable=False, comment='同一知识点连续错误次数'),
    sa.Column('consecutive_correct_count', sa.Integer(), server_default='0', nullable=False, comment='同一知识点连续正确次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['exam_record_id'], ['exam_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_parent_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生'),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='家长'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='绑定状态：active / inactive'),
    sa.Column('relationship', sa.String(length=20), server_default='other', nullable=False, comment='亲子关系：father / mother / other'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'parent_id', name='uq_binding_student_parent')
    )
    op.create_table('student_submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_record_id', sa.Integer(), nullable=False, comment='所属考试'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='班级（冗余，加速查询）'),
    sa.Column('original_image', sa.String(length=500), nullable=False, comment='原始答题卡图片路径'),
    sa.Column('graded_image', sa.String(length=500), nullable=True, comment='批改后图片路径（含批注）'),
    sa.Column('answer_list', sa.JSON(), nullable=True, comment='学生答案列表 JSON'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='总分'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False, comment='提交时间'),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True, comment='批改完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_record_id'], ['exam_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生'),
    sa.Column('warning_type', sa.String(length=30), nullable=False, comment='预警类型'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='严重级别：info / warning / severe'),
    sa.Column('message', sa.Text(), nullable=False, comment='预警消息文本'),
    sa.Column('notified_teacher', sa.Boolean(), server_default='0', nullable=False, comment='是否已通知教师'),
    sa.Column('notified_parent', sa.Boolean(), server_default='0', nullable=False, comment='是否已通知家长'),
    sa.Column('notified_student', sa.Boolean(), server_default='0', nullable=False, comment='是否已通知学生本人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_task_id', sa.Integer(), nullable=False, comment='所属复习任务'),
    sa.Column('level', sa.Integer(), nullable=False, comment='本次复习时的级别'),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False, comment='复习日期'),
    sa.Column('result', sa.Boolean(), nullable=False, comment='结果：True=答对，False=答错'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_history')
    op.drop_table('warning_log')
    op.drop_table('student_submission')
    op.drop_table('student_parent_binding')
    op.drop_table('student_answer')
    op.drop_table('review_task')
    op.drop_table('long_term_memory')
    with op.batch_alter_table('conversation_checkpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_checkpoint_thread_id'))

    op.drop_table('conversation_checkpoint')
    op.drop_table('teacher_class_subject')
    op.drop_table('student')
    op.drop_table('question_set_item')
    op.drop_table('ocr_task')
    op.drop_table('exam_record')
    op.drop_table('upload_session')
    op.drop_table('teacher_application')
    op.drop_table('question_set')
    op.drop_table('parent_notification')
    op.drop_table('class')
    op.drop_table('barrier_config')
    op.drop_table('teacher')
    op.drop_table('parent')
    op.drop_table('grade')
    op.drop_table('school')
    op.drop_table('question')
    op.drop_table('knowledge_point')
    op.drop_table('historical_exam')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_username'))

    op.drop_table('account')
    # ### end Alembic commands ###
